// Worldwide locations & comprehensive industries used across job filters and posting

const RAW_LOCATIONS: string[] = [
  // North America
  "New York, USA", "San Francisco, USA", "Los Angeles, USA", "Seattle, USA", "Austin, USA",
  "Boston, USA", "Chicago, USA", "Denver, USA", "Miami, USA", "Atlanta, USA",
  "Washington DC, USA", "Houston, USA", "Dallas, USA",
  "Toronto, Canada", "Vancouver, Canada", "Montreal, Canada", "Ottawa, Canada",
  "Mexico City, Mexico", "Guadalajara, Mexico",
  "Havana, Cuba", "Kingston, Jamaica", "Port-au-Prince, Haiti", "Santo Domingo, Dominican Republic",
  "San Juan, Puerto Rico", "Nassau, Bahamas",
  "Guatemala City, Guatemala", "San Salvador, El Salvador", "Tegucigalpa, Honduras",
  "Managua, Nicaragua", "San José, Costa Rica", "Panama City, Panama", "Belmopan, Belize",
  // South America
  "São Paulo, Brazil", "Rio de Janeiro, Brazil", "Brasília, Brazil",
  "Buenos Aires, Argentina", "Santiago, Chile", "Lima, Peru",
  "Bogotá, Colombia", "Medellín, Colombia", "Caracas, Venezuela",
  "Quito, Ecuador", "La Paz, Bolivia", "Asunción, Paraguay", "Montevideo, Uruguay",
  "Georgetown, Guyana", "Paramaribo, Suriname",
  // Europe — Western
  "London, UK", "Manchester, UK", "Edinburgh, UK", "Cardiff, UK", "Belfast, UK",
  "Dublin, Ireland", "Paris, France", "Lyon, France", "Marseille, France",
  "Berlin, Germany", "Munich, Germany", "Hamburg, Germany", "Frankfurt, Germany",
  "Amsterdam, Netherlands", "Rotterdam, Netherlands", "The Hague, Netherlands",
  "Brussels, Belgium", "Antwerp, Belgium", "Luxembourg City, Luxembourg",
  "Madrid, Spain", "Barcelona, Spain", "Valencia, Spain",
  "Lisbon, Portugal", "Porto, Portugal",
  "Rome, Italy", "Milan, Italy", "Naples, Italy",
  "Zurich, Switzerland", "Geneva, Switzerland", "Bern, Switzerland",
  "Vienna, Austria", "Salzburg, Austria",
  "Vaduz, Liechtenstein", "Monaco, Monaco", "Andorra la Vella, Andorra",
  "San Marino, San Marino", "Vatican City, Vatican",
  "Valletta, Malta", "Nicosia, Cyprus",
  // Europe — Nordics
  "Stockholm, Sweden", "Gothenburg, Sweden",
  "Copenhagen, Denmark", "Oslo, Norway", "Bergen, Norway",
  "Helsinki, Finland", "Reykjavík, Iceland",
  // Europe — Central & Eastern
  "Warsaw, Poland", "Kraków, Poland",
  "Prague, Czech Republic", "Bratislava, Slovakia",
  "Budapest, Hungary", "Bucharest, Romania", "Sofia, Bulgaria",
  "Athens, Greece", "Thessaloniki, Greece",
  "Belgrade, Serbia", "Zagreb, Croatia", "Sarajevo, Bosnia and Herzegovina",
  "Ljubljana, Slovenia", "Skopje, North Macedonia", "Podgorica, Montenegro",
  "Tirana, Albania", "Pristina, Kosovo",
  "Tallinn, Estonia", "Riga, Latvia", "Vilnius, Lithuania",
  "Minsk, Belarus", "Kyiv, Ukraine", "Chișinău, Moldova",
  "Moscow, Russia", "Saint Petersburg, Russia",
  "Istanbul, Turkey", "Ankara, Turkey",
  // Middle East
  "Dubai, UAE", "Abu Dhabi, UAE", "Tel Aviv, Israel", "Jerusalem, Israel",
  "Riyadh, Saudi Arabia", "Jeddah, Saudi Arabia",
  "Doha, Qatar", "Manama, Bahrain", "Kuwait City, Kuwait", "Muscat, Oman",
  "Amman, Jordan", "Beirut, Lebanon", "Damascus, Syria", "Baghdad, Iraq",
  "Tehran, Iran", "Sana'a, Yemen",
  // Africa
  "Cairo, Egypt", "Alexandria, Egypt",
  "Lagos, Nigeria", "Abuja, Nigeria",
  "Nairobi, Kenya", "Kampala, Uganda", "Dar es Salaam, Tanzania", "Dodoma, Tanzania",
  "Kigali, Rwanda", "Bujumbura, Burundi", "Addis Ababa, Ethiopia", "Asmara, Eritrea",
  "Djibouti, Djibouti", "Mogadishu, Somalia",
  "Cape Town, South Africa", "Johannesburg, South Africa", "Pretoria, South Africa",
  "Maputo, Mozambique", "Harare, Zimbabwe", "Lusaka, Zambia", "Lilongwe, Malawi",
  "Gaborone, Botswana", "Windhoek, Namibia", "Maseru, Lesotho", "Mbabane, Eswatini",
  "Antananarivo, Madagascar", "Port Louis, Mauritius", "Victoria, Seychelles",
  "Luanda, Angola", "Kinshasa, DR Congo", "Brazzaville, Congo", "Libreville, Gabon",
  "Yaoundé, Cameroon", "Malabo, Equatorial Guinea", "Bangui, Central African Republic",
  "N'Djamena, Chad", "Khartoum, Sudan", "Juba, South Sudan",
  "Accra, Ghana", "Abidjan, Ivory Coast", "Yamoussoukro, Ivory Coast",
  "Dakar, Senegal", "Banjul, Gambia", "Bissau, Guinea-Bissau", "Conakry, Guinea",
  "Freetown, Sierra Leone", "Monrovia, Liberia", "Bamako, Mali",
  "Ouagadougou, Burkina Faso", "Niamey, Niger", "Nouakchott, Mauritania",
  "Lomé, Togo", "Porto-Novo, Benin", "Cotonou, Benin",
  "Algiers, Algeria", "Tunis, Tunisia", "Tripoli, Libya", "Rabat, Morocco", "Casablanca, Morocco",
  // Asia — East
  "Tokyo, Japan", "Osaka, Japan", "Kyoto, Japan",
  "Seoul, South Korea", "Busan, South Korea", "Pyongyang, North Korea",
  "Beijing, China", "Shanghai, China", "Shenzhen, China", "Guangzhou, China",
  "Hong Kong", "Macau", "Taipei, Taiwan",
  "Ulaanbaatar, Mongolia",
  // Asia — Southeast
  "Singapore", "Bangkok, Thailand", "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia", "Manila, Philippines",
  "Ho Chi Minh City, Vietnam", "Hanoi, Vietnam", "Phnom Penh, Cambodia",
  "Vientiane, Laos", "Naypyidaw, Myanmar", "Yangon, Myanmar",
  "Bandar Seri Begawan, Brunei", "Dili, Timor-Leste",
  // Asia — South
  "Mumbai, India", "Delhi, India", "Bangalore, India", "Hyderabad, India",
  "Chennai, India", "Pune, India", "Kolkata, India",
  "Karachi, Pakistan", "Lahore, Pakistan", "Islamabad, Pakistan",
  "Dhaka, Bangladesh", "Colombo, Sri Lanka", "Sri Jayawardenepura Kotte, Sri Lanka",
  "Kathmandu, Nepal", "Thimphu, Bhutan", "Malé, Maldives", "Kabul, Afghanistan",
  // Asia — Central
  "Astana, Kazakhstan", "Almaty, Kazakhstan", "Tashkent, Uzbekistan",
  "Bishkek, Kyrgyzstan", "Dushanbe, Tajikistan", "Ashgabat, Turkmenistan",
  // Caucasus
  "Baku, Azerbaijan", "Tbilisi, Georgia", "Yerevan, Armenia",
  // Oceania
  "Sydney, Australia", "Melbourne, Australia", "Brisbane, Australia",
  "Perth, Australia", "Canberra, Australia", "Adelaide, Australia",
  "Auckland, New Zealand", "Wellington, New Zealand", "Christchurch, New Zealand",
  "Suva, Fiji", "Port Moresby, Papua New Guinea", "Honiara, Solomon Islands",
  "Port Vila, Vanuatu", "Apia, Samoa", "Nuku'alofa, Tonga",
  "Tarawa, Kiribati", "Funafuti, Tuvalu", "Yaren, Nauru",
  "Palikir, Micronesia", "Majuro, Marshall Islands", "Ngerulmud, Palau",
];

export const WORLD_LOCATIONS: string[] = [
  "Remote",
  "Hybrid",
  ...Array.from(new Set(RAW_LOCATIONS)).sort((a, b) =>
    a.localeCompare(b, undefined, { sensitivity: "base" })
  ),
];

export const INDUSTRIES: string[] = [
  "Accounting",
  "Advertising & Marketing",
  "Aerospace",
  "Agriculture",
  "Architecture",
  "Artificial Intelligence",
  "AR/VR",
  "Automotive",
  "B2B",
  "B2C",
  "Banking & Finance",
  "Beauty & Wellness",
  "Biotechnology",
  "Blockchain & Crypto",
  "Childcare",
  "Climate Tech",
  "Cloud Infrastructure",
  "Construction",
  "Consulting",
  "Consumer Goods",
  "Consumer Tech",
  "Cybersecurity",
  "Data & Analytics",
  "Defense",
  "E-commerce",
  "Education",
  "EdTech",
  "Elder Care",
  "Energy",
  "Enterprise Software",
  "Environmental Services",
  "Fashion & Apparel",
  "Film & Television",
  "Fintech",
  "Food & Beverage",
  "Gaming",
  "Government",
  "Healthcare",
  "Hospitality",
  "Human Resources",
  "Insurance",
  "IoT & Hardware",
  "Legal Services",
  "Logistics & Supply Chain",
  "Machine Learning",
  "Manufacturing",
  "Marketplace",
  "Media & Entertainment",
  "Medical Devices",
  "Mining",
  "Music",
  "Non-Profit",
  "Oil & Gas",
  "Pharmaceuticals",
  "Public Relations",
  "Publishing",
  "Real Estate",
  "Recruiting",
  "Renewable Energy",
  "Research & Development",
  "Retail",
  "Robotics",
  "SaaS",
  "Social Media",
  "Space",
  "Sports & Fitness",
  "Startups",
  "Telecommunications",
  "Transportation",
  "Travel & Tourism",
  "Utilities",
  "Veterinary",
  "Waste Management",
];
