// Worldwide locations & comprehensive industries used across job filters and posting

export const WORLD_LOCATIONS: string[] = [
  "Remote",
  "Hybrid",
  // North America
  "New York, USA", "San Francisco, USA", "Los Angeles, USA", "Seattle, USA", "Austin, USA",
  "Boston, USA", "Chicago, USA", "Denver, USA", "Miami, USA", "Atlanta, USA",
  "Washington DC, USA", "Houston, USA", "Dallas, USA", "Toronto, Canada", "Vancouver, Canada",
  "Montreal, Canada", "Ottawa, Canada", "Mexico City, Mexico", "Guadalajara, Mexico",
  // South America
  "São Paulo, Brazil", "Rio de Janeiro, Brazil", "Buenos Aires, Argentina", "Santiago, Chile",
  "Lima, Peru", "Bogotá, Colombia", "Medellín, Colombia",
  // Europe
  "London, UK", "Manchester, UK", "Edinburgh, UK", "Dublin, Ireland",
  "Paris, France", "Lyon, France", "Berlin, Germany", "Munich, Germany", "Hamburg, Germany",
  "Frankfurt, Germany", "Amsterdam, Netherlands", "Rotterdam, Netherlands",
  "Brussels, Belgium", "Madrid, Spain", "Barcelona, Spain", "Lisbon, Portugal", "Porto, Portugal",
  "Rome, Italy", "Milan, Italy", "Zurich, Switzerland", "Geneva, Switzerland",
  "Vienna, Austria", "Stockholm, Sweden", "Copenhagen, Denmark", "Oslo, Norway",
  "Helsinki, Finland", "Warsaw, Poland", "Prague, Czech Republic", "Budapest, Hungary",
  "Bucharest, Romania", "Athens, Greece", "Istanbul, Turkey",
  // Middle East & Africa
  "Dubai, UAE", "Abu Dhabi, UAE", "Tel Aviv, Israel", "Riyadh, Saudi Arabia",
  "Doha, Qatar", "Cairo, Egypt", "Lagos, Nigeria", "Nairobi, Kenya",
  "Cape Town, South Africa", "Johannesburg, South Africa",
  // Asia
  "Tokyo, Japan", "Osaka, Japan", "Seoul, South Korea", "Beijing, China",
  "Shanghai, China", "Shenzhen, China", "Hong Kong", "Taipei, Taiwan",
  "Singapore", "Bangkok, Thailand", "Kuala Lumpur, Malaysia", "Jakarta, Indonesia",
  "Manila, Philippines", "Ho Chi Minh City, Vietnam", "Hanoi, Vietnam",
  "Mumbai, India", "Delhi, India", "Bangalore, India", "Hyderabad, India",
  "Chennai, India", "Pune, India", "Karachi, Pakistan", "Lahore, Pakistan",
  "Dhaka, Bangladesh",
  // Oceania
  "Sydney, Australia", "Melbourne, Australia", "Brisbane, Australia", "Perth, Australia",
  "Auckland, New Zealand", "Wellington, New Zealand",
];

export const INDUSTRIES: string[] = [
  "SaaS",
  "Fintech",
  "Banking & Finance",
  "Insurance",
  "Healthcare",
  "Pharmaceuticals",
  "Biotechnology",
  "Medical Devices",
  "E-commerce",
  "Retail",
  "Consumer Goods",
  "Fashion & Apparel",
  "Food & Beverage",
  "Hospitality",
  "Travel & Tourism",
  "Real Estate",
  "Construction",
  "Architecture",
  "Manufacturing",
  "Automotive",
  "Aerospace",
  "Defense",
  "Energy",
  "Oil & Gas",
  "Renewable Energy",
  "Utilities",
  "Mining",
  "Agriculture",
  "Logistics & Supply Chain",
  "Transportation",
  "Telecommunications",
  "Media & Entertainment",
  "Gaming",
  "Music",
  "Film & Television",
  "Publishing",
  "Advertising & Marketing",
  "Public Relations",
  "Education",
  "EdTech",
  "Non-Profit",
  "Government",
  "Legal Services",
  "Consulting",
  "Accounting",
  "Human Resources",
  "Recruiting",
  "Cybersecurity",
  "Cloud Infrastructure",
  "Artificial Intelligence",
  "Machine Learning",
  "Data & Analytics",
  "Blockchain & Crypto",
  "IoT & Hardware",
  "Robotics",
  "AR/VR",
  "Consumer Tech",
  "B2B",
  "B2C",
  "Marketplace",
  "Social Media",
  "Sports & Fitness",
  "Beauty & Wellness",
  "Childcare",
  "Elder Care",
  "Veterinary",
  "Environmental Services",
  "Waste Management",
  "Climate Tech",
  "Space",
  "Research & Development",
  "Startups",
  "Enterprise Software",
];
