import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Job } from "@/lib/types";
import { Link as LinkIcon, Pencil, Printer, Globe } from "lucide-react";
import { toast } from "sonner";
import { useJobStore } from "@/lib/store";
import { useAuth } from "@/contexts/AuthContext";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  job: Job | null;
  /** When true, show Publish + Edit actions (used in history re-preview). */
  showPublishAndEdit?: boolean;
  onEdit?: (job: Job) => void;
  onPublished?: (job: Job) => void;
}

const buildShareablePayload = (job: Job) => {
  // Encode the job into a URL-safe base64 fragment so it can be previewed without a backend
  const json = JSON.stringify(job);
  const b64 = btoa(unescape(encodeURIComponent(json)));
  return `${window.location.origin}/job-preview#${b64}`;
};

const JobPreviewDialog = ({ open, onOpenChange, job, showPublishAndEdit, onEdit, onPublished }: Props) => {
  const { user } = useAuth();
  const { addExportHistory, jobs, addJob, updateJob } = useJobStore();
  if (!job) return null;

  const recordExport = (type: "share-link" | "pdf", shareUrl: string) => {
    if (!user || !job) return;
    addExportHistory({
      id: crypto.randomUUID(),
      companyId: user.id,
      jobSnapshot: job,
      shareUrl,
      createdAt: new Date(),
      type,
    });
  };

  const handlePrintPdf = () => {
    const w = window.open("", "_blank", "width=900,height=1000");
    if (!w) {
      toast.error("Unable to open print window. Allow pop-ups and try again.");
      return;
    }
    const html = `<!doctype html><html><head><title>${job.title} — ${job.companyName}</title>
<meta charset="utf-8"/>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;color:#111;max-width:780px;margin:32px auto;padding:0 24px;line-height:1.55;}
  h1{font-size:28px;margin:0 0 4px;} h2{font-size:16px;margin:24px 0 8px;text-transform:uppercase;letter-spacing:.05em;color:#444;}
  .meta{color:#555;font-size:14px;margin-bottom:16px;}
  .badges span{display:inline-block;background:#eef;color:#225;padding:2px 8px;border-radius:999px;font-size:12px;margin:0 6px 6px 0;}
  ul{margin:0;padding-left:20px;} li{margin:4px 0;}
  .footer{margin-top:40px;border-top:1px solid #ddd;padding-top:12px;color:#888;font-size:12px;}
  @media print { @page { margin: 16mm; } }
</style></head><body>
<h1>${job.title}</h1>
<div class="meta"><strong>${job.companyName}</strong> · ${job.location} · ${job.type} · ${job.experienceRequired}${job.salary ? ` · ${job.salary}` : ""}</div>
<h2>Description</h2><p>${job.description.replace(/\n/g, "<br/>")}</p>
<h2>Requirements</h2><ul>${job.requirements.map((r) => `<li>${r}</li>`).join("")}</ul>
<h2>Preferred Skills</h2><ul>${job.preferredSkills.map((r) => `<li>${r}</li>`).join("")}</ul>
${job.industryExperience?.length ? `<h2>Industry Experience</h2><div class="badges">${job.industryExperience.map((t) => `<span>${t}</span>`).join("")}</div>` : ""}
${job.softSkills?.length ? `<h2>Soft Skills</h2><div class="badges">${job.softSkills.map((t) => `<span>${t}</span>`).join("")}</div>` : ""}
${job.culturalFit?.length ? `<h2>Cultural Fit</h2><div class="badges">${job.culturalFit.map((t) => `<span>${t}</span>`).join("")}</div>` : ""}
<div class="footer">Generated by HireAI · Preview before publishing</div>
<script>window.onload = () => { window.focus(); window.print(); };</script>
</body></html>`;
    w.document.write(html);
    w.document.close();
    recordExport("pdf", buildShareablePayload(job));
  };

  const handleCopyLink = async () => {
    const url = buildShareablePayload(job);
    try {
      await navigator.clipboard.writeText(url);
      toast.success("Shareable preview link copied to clipboard");
      recordExport("share-link", url);
    } catch {
      toast.error("Could not copy link. Long-press the URL to copy: " + url.slice(0, 60) + "…");
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Preview · {job.title}</DialogTitle>
        </DialogHeader>

        <article className="space-y-4 text-sm">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">{job.title}</h1>
            <p className="text-muted-foreground mt-1">
              <strong>{job.companyName}</strong> · {job.location} · {job.type} · {job.experienceRequired}
              {job.salary ? ` · ${job.salary}` : ""}
            </p>
          </div>

          <section>
            <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-1">Description</h3>
            <p className="whitespace-pre-line leading-relaxed">{job.description}</p>
          </section>

          <section>
            <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-1">Requirements</h3>
            <ul className="list-disc pl-5 space-y-1">{job.requirements.map((r, i) => <li key={i}>{r}</li>)}</ul>
          </section>

          <section>
            <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-1">Preferred Skills</h3>
            <ul className="list-disc pl-5 space-y-1">{job.preferredSkills.map((r, i) => <li key={i}>{r}</li>)}</ul>
          </section>

          {!!job.industryExperience?.length && (
            <section>
              <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-1">Industry</h3>
              <div className="flex flex-wrap gap-1.5">{job.industryExperience.map((t) => <Badge key={t} variant="secondary">{t}</Badge>)}</div>
            </section>
          )}
          {!!job.softSkills?.length && (
            <section>
              <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-1">Soft Skills</h3>
              <div className="flex flex-wrap gap-1.5">{job.softSkills.map((t) => <Badge key={t} variant="secondary">{t}</Badge>)}</div>
            </section>
          )}
          {!!job.culturalFit?.length && (
            <section>
              <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-1">Cultural Fit</h3>
              <div className="flex flex-wrap gap-1.5">{job.culturalFit.map((t) => <Badge key={t} variant="secondary">{t}</Badge>)}</div>
            </section>
          )}
        </article>

        <DialogFooter className="gap-2 sm:gap-2">
          <Button variant="outline" onClick={handleCopyLink}>
            <LinkIcon className="h-4 w-4 mr-2" /> Copy share link
          </Button>
          <Button onClick={handlePrintPdf}>
            <Printer className="h-4 w-4 mr-2" /> Export PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default JobPreviewDialog;
